# Generated by Django 5.2.7 on 2025-11-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("correct_answers", models.PositiveIntegerField()),
                ("incorrect_answers", models.PositiveIntegerField()),
                ("mastery_change", models.FloatField(default=0.0)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("notes_used_count", models.PositiveIntegerField(default=0)),
                ("flashcards_reviewed_count", models.PositiveIntegerField(default=0)),
                ("quizzes_taken_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mastery_score", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
