# Generated by Django 5.2.7 on 2025-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
