# Generated by Django 5.2.7 on 2025-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="processed_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
