# Generated by Django 5.2.7 on 2025-12-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_uploadedfile_processed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="flashcards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="key_points",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="quiz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
